apiVersion: v1
kind: Service
metadata:
  name: secretproxy
  namespace: proxy-system
  labels:
    app: secretproxy
spec:
  type: ClusterIP
  selector:
    app: secretproxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
